kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.serviceAccount }}
  labels: 
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: cloudflow
automountServiceAccountToken: true