kind: Deployment
apiVersion: apps/v1
metadata:
  name: cloudflow-operator
  labels:
    app: "cloudflow-operator"
{{- include "cloudflow.labels" . | indent 4 }}
spec:
  selector:
      matchLabels:
        app: {{ .Values.cloudflow_operator.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.cloudflow_operator.name }}
{{- include "cloudflow.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ .Values.cloudflow_operator.name }}
      automountServiceAccountToken: true
      containers:
        - name: {{ .Values.cloudflow_operator.name }}
          image: "{{ .Values.cloudflow_operator.image.name }}:{{ .Values.cloudflow_operator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.cloudflow_operator.image.pullPolicy }}
          ports:
            - containerPort: 5001
              name: http
          resources:
            requests:
              memory: {{ required "Requested pod memory must be set" .Values.cloudflow_operator.resources.requests.memory }}
              cpu: {{ required "Requested pod cpu must be set" .Values.cloudflow_operator.resources.requests.cpu }}
            limits:
              memory: {{ required "Max pod memory must be set" .Values.cloudflow_operator.resources.limits.memory }}
              cpu: {{ required "Max pod cpu must be set" .Values.cloudflow_operator.resources.limits.cpu }}
          env:
            - name: JAVA_OPTS
              value: {{ .Values.cloudflow_operator.jvm.opts }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{.Values.kafkaClusters.default.bootstrapServers}}"
            - name: AKKA_RUNNER_REQUESTS_MEMORY
              value: "{{ .Values.cloudflow_operator.akkaRunner.requestsMemory }}"
            - name: AKKA_RUNNER_REQUESTS_CPU
              value: "{{ .Values.cloudflow_operator.akkaRunner.requestsCpu }}"
            - name: AKKA_RUNNER_LIMITS_MEMORY
              value: "{{ .Values.cloudflow_operator.akkaRunner.limitsMemory }}"
            - name: SPARK_EXECUTOR_REQUESTS_MEMORY
              value: "{{ .Values.cloudflow_operator.sparkExecutor.requestsMemory }}"
            - name: SPARK_EXECUTOR_REQUESTS_CPU
              value: "{{ .Values.cloudflow_operator.sparkExecutor.requestsCpu }}"
            - name: SPARK_DRIVER_REQUESTS_MEMORY
              value: "{{ .Values.cloudflow_operator.sparkDriver.requestsMemory }}"
            - name: SPARK_DRIVER_REQUESTS_CPU
              value: "{{ .Values.cloudflow_operator.sparkDriver.requestsCpu }}"
            - name: RELEASE_VERSION
              value: "{{ .Chart.Version }}"
            # Expose pod meta information to operator
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOGLEVEL_ROOT
              value: "{{ .Values.cloudflow_operator.logLevelRoot | default "INFO" }}"
            - name: LOGLEVEL_AKKA
              value: "{{ .Values.cloudflow_operator.logLevelAkka | default "INFO" }}"
            - name: LOGLEVEL_SKUBER
              value: "{{ .Values.cloudflow_operator.logLevelSkuber | default "WARN" }}"
          readinessProbe:
            httpGet:
              path: /checks/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /checks/healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
