kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloudflow-operator-bindings
  labels:
{{- include "cloudflow.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.cloudflow_operator.name }}
subjects:
  - kind: ServiceAccount
    name: cloudflow-operator
    namespace: {{.Release.Namespace}}
