apiVersion: v1
description: A Helm chart for installing Cloudflow
name: cloudflow
version: 0.0.1-back-to-core-20210504
appVersion: 0.0.1-back-to-core-20210504
home: https://cloudflow.io
icon: https://cloudflow.io/_/img/cloudflow-icon-full-color-flush.svg
