apiVersion: v1
description: A Helm chart for installing Cloudflow
name: cloudflow
version: 0.0.0-NIGHTLY30112020
appVersion: 0.0.0-NIGHTLY30112020
home: https://cloudflow.io
icon: https://cloudflow.io/_/img/cloudflow-icon-full-color-flush.svg
