cloudflow_operator:
  name: "cloudflow-operator"
  image: 
    name: lightbend/cloudflow-operator
    pullPolicy: "IfNotPresent"
  resources:
    requests:
      cpu: "0.1"
      memory: "256M"
    limits:
      cpu: "0.5"
      memory: "1G"
  ## Akka runner settings
  akkaRunner:
    requestsMemory: "128M"
    requestsCpu: "0.5"
    limitsMemory: "2048M"
  sparkDriver:
    requestsCpu: "0.5"
    requestsMemory: "512M"
  sparkExecutor:
    requestsCpu: "1"
    requestsMemory: "2G"
  ## JVM command line options
  jvm:
    opts: -XX:MaxRAMPercentage=90.0 -XX:+UseContainerSupport
  controlled_namespace: null

# Named Kafka cluster settings
kafkaClusters:
  default:
    bootstrapServers:
    partitions: 53
    replicas: 2
    connectionConfig: {}
    # more config can be added here from Kafka ProducerConfig (see org.apache.kafka.clients.producer.ProducerConfig)
    producerConfig: {}
    # more config can be added here from Kafka ConsumerConfig (see org.apache.kafka.clients.consumer.ConsumerConfig)
    consumerConfig: {}
