cloudflow_operator:
  version: "2.0.7"
  name: "cloudflow-operator"
  persistentStorageClass: standard
  kafkaBootstrapservers:
  image: 
    name: lightbend/cloudflow-operator
    pullPolicy: "IfNotPresent"
  resources:
    requests:
      cpu: "0.1"
      memory: "256M"
    limits:
      cpu: "0.5"
      memory: "512M"
  ## Akka runner settings
  akkaRunner:
    requestsMemory: "128M"
    requestsCpu: "0.5"
    limitsMemory: "2048M"
  sparkDriver:
    requestsCpu: "0.5"
    requestsMemory: "512M"
  sparkExecutor:
    requestsCpu: "1"
    requestsMemory: "2G"
  ## JVM command line options
  jvm:
    opts: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
